POST http://localhost:3000/getToken
Content-Type: application/json

{
    "username": "alice",
    "password": "password123"
}

###
GET http://localhost:3000/cards?set=Base%20Set&type=Creature&rarity=Common

###
POST http://localhost:3000/cards/create
Content-Type: application/json

{
    "id": 126,
    "name": "asdfd Magus",
    "set": "Base Set",
    "cardNumber": 1,
    "type": "Creature",
    "power": 3000,
    "toughness": 2500,
    "rarity": "Common",
    "cost": 3
}

###
PUT http://localhost:3000/cards/13
Content-Type: application/json

{
    "id": 126,
    "name": "asdfd Magus",
    "set": "Base Set",
    "cardNumber": 1,
    "type": "Creature",
    "power": 3000,
    "toughness": 2500,
    "rarity": "Common",
    "cost": 3
}